export const ROUTES = {
    HOMEPAGE: "/",
    LOGIN:"login",
    PROFILE:"profile",
    DOCTOR_FORM:"add_doctor",
    DOCTOR_UPDATE_FORM:"update_form",
    DOCTOR_MANAGE:"doctor_manage",
    LAB_MANAGE:"lab_manage",
    LAB_FORM:"lab_form",
    UPDATE_LAB_FORM: "Update_lab",
    LAB_ASISTANT:"lab_assistant",
    ALL_TEST:"tests",
    CURRENT_ORDERS_LAB:"lab_orders",
    HISTORY_ORDERS_LAB:"completed_orders",
    TEST_FORM:"test_form",
    CITY:"cities",
    DOCTOR_BOOKING:'doctor-booking',
    HISTORY_DOCTOR_BOOKING:'history-doctor-booking',
    TEST_TO_LAB:"test_to_lab",
    ASSIGN_TEST:"test_assign",
    PHARMACY_MANAGE:"pharmacy_manage",
    LAB_BOOKING: "lab_booking_details",
    DOCTOR_REPORT: "doctor_report",
    ASSIGN_DOCTOR: "doctor-assign",
    SPECIALIST_DOCTOR_UPDATE: "doctor_specialist_update",
    CATEGORY_DOCTOR_UPDATE: "doctor_category_update",
    LAB_REPORT: "lab_report",
    ORDER_REPORT: "order_report",
    INSURANCE_REPORT: "insurance_report",
    PHLEBOTOMIST_REPORT: "phlebotomist_report",
    USER_DOCTOR_BOOKING_REPORT: "doctor_booking_report",
    USER_LAB_BOOKING_REPORT: "lab_booking_report",
    ADD_POPUP:"add-popup",
    USER_MANAGE:"user_manage",
    PHARMACY_FORM:"pharmacy_form",
    PRODUCT_FORM:"product_form",
    PRODUCT_UPDATE_FORM:"product_update_form",
    PRODUCT_UPLOAD_FORM:"product-upload",
    BRAND_FORM:"brand_form",
    PROMO_CODE:"promo_codes",
    NEWS_LETTER:"news_letter",
    CONATCT_US:"contact_us",
    BANNERS:"banners",
    PUSH_NOTIFICATION:"push-notification",
    CATEGORY_FORM:"category-form",
    CATEGORY_MANAGE: "manage-category",
    BRAND_MANAGE: "manage-brand",
    BRAND_UPDATE: "update-brand",
    CATEGORY_UPDATE: "update-category",
    USER_FORM:"user_form",
    USER_UPDATE_FORM:"user_update_form",
    INSURANCE_PROVIDER_FORM:"provider-form",
    DOCTOR_BOOKING_DETAILS:"booking-details",
    DOCTOR_BOOKING_DETAIL:"booking-detail",
    INSURANCE_PACKAGE_FORM:"package-form",
    INSURANCE_PACKAGE_MANAGE:"package-manage",
    INSURANCE_PROVIDER_MANAGE:"provider-manage",
    SPECIALIST: "specialist",
    DOCTOR_TYPE:"doctor_type",
    PRODUCT_TRACKING:"product_track",
    ALL_ORDERS:"all_orders",
    UPDATE_INSURANCE_PACKAGE:"update_package",
    UPDATE_INSURANCE_PROVIDER:"update_provider",
    ALL_INSURANCE_BOOKING:"insurance_booking",
    INSURANCE_PROVIDER_BOOKING:"provider_booking",

}

